### PR TITLE
New hapi changes and improved project structure

### PR DESCRIPTION
**Pull request by xDAnkit**
1. Updated to **Hapi 17.2.2** with new **server.route option** method,
2. Updated all npm packages.
3. Removed **api/ prefix route** from config file to make swagger bit more clear for differentiating between multiple api's.
4. Moved all routes and components to new **api** folder which improves the overall code structure bit more clear.

### CODE REVIEW

**Comment by Wesseldr** [comment]
Like your thoughts! thank you for supplying the patch, hope it gets merged

**Comment by Talento90** [comment]
Build it's broken! Could you please fix it?

**Comment by leonardocintra** [comment]
@xDAnkit fixed erros ?

**Comment by xDAnkit** [comment]
Hello guys, Sorry for late reply. Creating a new pull request with stable code base.
@Talento90 - You can merge the new pull request.

**Comment by xDAnkit** [comment]
Thanks @Talento90 for the merging the pull request.

**Pull request closed without merging**
